# Generated by Django 3.0.8 on 2020-07-06 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
    ]
