# Generated by Django 3.0.8 on 2020-07-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodbank', '0004_auto_20200708_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='donors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
    ]
