# Generated by Django 3.0.8 on 2020-07-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0007_auto_20200720_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='status',
        ),
        migrations.AlterField(
            model_name='donor',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
    ]
