# Generated by Django 3.0.7 on 2021-02-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0011_auto_20210205_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.ForeignKey(help_text='Enter your county of residence', null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodbank.County'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subCounty',
            field=models.ForeignKey(help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.SubCounty'),
        ),
    ]
