# Generated by Django 3.0.7 on 2021-02-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0016_auto_20210205_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.CharField(help_text='Enter hospital name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientName',
            field=models.CharField(help_text='Enter patient name', max_length=250, null=True),
        ),
    ]
