# Generated by Django 3.0.7 on 2021-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0017_auto_20210205_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalName',
            field=models.CharField(default='', help_text='Enter hospital name', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientName',
            field=models.CharField(default='', help_text='Enter patient name', max_length=250),
        ),
    ]
