# Generated by Django 3.0.7 on 2021-02-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0020_auto_20210206_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospitalName',
            field=models.CharField(help_text='Enter hospital name', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientName',
            field=models.CharField(help_text='Enter patient name', max_length=250),
        ),
    ]
