# Generated by Django 3.0.7 on 2021-02-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0021_auto_20210206_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderEmail', models.CharField(help_text='Enter an email address', max_length=200)),
                ('contact', models.IntegerField(help_text='Enter your contact number')),
                ('sentDate', models.DateField(auto_now_add=True)),
                ('messsage', models.TextField(help_text='Write your message')),
                ('status', models.CharField(choices=[('r', 'Read'), ('un', 'Unread')], default=0, help_text='MESSAGE_STATUS', max_length=10)),
                ('senderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.Donor')),
            ],
        ),
        migrations.RemoveField(
            model_name='patientmessage',
            name='patient',
        ),
        migrations.DeleteModel(
            name='DonorMessage',
        ),
        migrations.DeleteModel(
            name='PatientMessage',
        ),
    ]
