# Generated by Django 3.0.7 on 2021-02-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0022_auto_20210207_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messsage',
            new_name='message',
        ),
    ]
