# Generated by Django 3.0.7 on 2021-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0025_auto_20210207_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[(1, 'Read'), (0, 'Unread')], default='Unread', help_text='MESSAGE_STATUS', max_length=10),
        ),
    ]
