# Generated by Django 3.0.7 on 2021-02-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0026_auto_20210207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('un', 'Unread'), ('r', 'Read')], default=0, help_text='MESSAGE_STATUS', max_length=10),
        ),
    ]
