# Generated by Django 3.0.7 on 2021-02-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0027_auto_20210207_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='senderName',
            field=models.CharField(help_text='Enter an email address', max_length=200),
        ),
    ]
