# Generated by Django 3.0.7 on 2021-02-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0030_auto_20210209_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospitalName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patientName',
        ),
    ]
