# Generated by Django 3.0.7 on 2021-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0031_auto_20210219_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospitalName',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientName',
            field=models.TextField(default='', max_length=100),
        ),
    ]
