# Generated by Django 3.0.7 on 2021-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0032_auto_20210219_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospitalName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientName',
            field=models.TextField(),
        ),
    ]
