# Generated by Django 3.0.7 on 2021-02-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0033_auto_20210219_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('un', 'Unread'), ('r', 'Read')], default='un', help_text='MESSAGE_STATUS', max_length=10),
        ),
    ]
