# Generated by Django 3.1.7 on 2021-03-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0035_auto_20210226_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospitalName',
        ),
        migrations.AddField(
            model_name='message',
            name='messsage',
            field=models.TextField(default='', help_text='Write your message here'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.CharField(default='', help_text='Enter hospital name', max_length=250),
        ),
        migrations.AlterField(
            model_name='county',
            name='countyName',
            field=models.TextField(default='', help_text='Enter county name'),
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.IntegerField(help_text='Enter count number', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.ForeignKey(default='', help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.county'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=models.ImageField(help_text='Attach your photo', upload_to=''),
        ),
        migrations.AlterField(
            model_name='donor',
            name='subCounty',
            field=models.ForeignKey(default='', help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.subcounty'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.donor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderName',
            field=models.TextField(help_text='Enter your contact number'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sentDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('r', 'Read'), ('un', 'Unread')], default=0, help_text='MESSAGE_STATUS', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='county',
            field=models.ForeignKey(default='', help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.county'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(help_text='Attach your photo', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientName',
            field=models.CharField(help_text='Enter patient name', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subCounty',
            field=models.ForeignKey(default='', help_text='Enter your county of residence', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.subcounty'),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.county'),
        ),
    ]
